on: push

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${PASSWORD}"
      - run: echo -e "${PASSWORD:0:1}\u200b${PASSWORD#?}"
